repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
        language: python
    -   id: end-of-file-fixer
        language: python
    -   id: check-yaml
-   repo: https://github.com/ambv/black
    rev: 23.3.0
    hooks:
    -   id: black
        language_version: python3.11
