# Generated by Django 4.2 on 2023-04-25 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gameresults',
            options={},
        ),
        migrations.AlterModelOptions(
            name='nabladminstatrecords',
            options={},
        ),
        migrations.AlterModelOptions(
            name='seriesstatrecords',
            options={},
        ),
        migrations.AlterModelOptions(
            name='statrecords',
            options={},
        ),
        migrations.AlterModelOptions(
            name='teamresults',
            options={'verbose_name_plural': 'Team Results'},
        ),
    ]
