# Generated by Django 4.2 on 2023-04-26 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0006_players_unique_bbrefid'),
        ('league', '0001_initial'),
        ('stats', '0002_alter_gameresults_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NabladminStatrecords',
        ),
        migrations.AddField(
            model_name='gameresults',
            name='homepitcher',
            field=models.ForeignKey(blank=True, db_column='homepitcher', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gameresults_homepitcher', to='player.players'),
        ),
        migrations.AddField(
            model_name='gameresults',
            name='scheduleid',
            field=models.ForeignKey(db_column='scheduleid', default=0, on_delete=django.db.models.deletion.CASCADE, to='league.schedules'),
        ),
        migrations.AddField(
            model_name='gameresults',
            name='visitpitcher',
            field=models.ForeignKey(blank=True, db_column='visitpitcher', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gameresults_visitpitcher', to='player.players'),
        ),
        migrations.AddField(
            model_name='seriesstatrecords',
            name='playerid',
            field=models.ForeignKey(db_column='playerid', default=0, on_delete=django.db.models.deletion.CASCADE, to='player.players'),
        ),
        migrations.AddField(
            model_name='seriesstatrecords',
            name='reportingteamid',
            field=models.ForeignKey(db_column='reportingteamid', default=0, on_delete=django.db.models.deletion.CASCADE, related_name='reportteam', to='league.teams'),
        ),
        migrations.AddField(
            model_name='seriesstatrecords',
            name='series',
            field=models.ForeignKey(db_column='series', default=0, on_delete=django.db.models.deletion.CASCADE, to='league.schedules'),
        ),
        migrations.AddField(
            model_name='seriesstatrecords',
            name='statsteamid',
            field=models.ForeignKey(db_column='statsteamid', default=0, on_delete=django.db.models.deletion.CASCADE, related_name='statsteam', to='league.teams'),
        ),
        migrations.AddField(
            model_name='statrecords',
            name='playerid',
            field=models.ForeignKey(db_column='playerid', default=0, on_delete=django.db.models.deletion.CASCADE, to='player.players'),
        ),
        migrations.AddField(
            model_name='statrecords',
            name='teamid',
            field=models.ForeignKey(db_column='teamid', default=0, on_delete=django.db.models.deletion.CASCADE, to='league.teams'),
        ),
        migrations.AddField(
            model_name='teamresults',
            name='divisionid',
            field=models.ForeignKey(db_column='divisionid', default=0, on_delete=django.db.models.deletion.CASCADE, to='league.divisions'),
        ),
        migrations.AddField(
            model_name='teamresults',
            name='leagueid',
            field=models.ForeignKey(db_column='leagueid', default=0, on_delete=django.db.models.deletion.CASCADE, to='league.leagues'),
        ),
        migrations.AddField(
            model_name='teamresults',
            name='teamid',
            field=models.ForeignKey(db_column='teamid', default=0, on_delete=django.db.models.deletion.CASCADE, to='league.teams'),
        ),
        migrations.AlterField(
            model_name='teamresults',
            name='divisionloss',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teamresults',
            name='divisiontitle',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teamresults',
            name='divisionwin',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teamresults',
            name='worldseriesapp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teamresults',
            name='worldserieswin',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='gameresults',
            unique_together={('scheduleid', 'gamenumber')},
        ),
        migrations.AlterUniqueTogether(
            name='seriesstatrecords',
            unique_together={('series', 'reportingteamid', 'statsteamid', 'season', 'playerid')},
        ),
        migrations.AlterUniqueTogether(
            name='statrecords',
            unique_together={('playerid', 'season', 'teamid')},
        ),
        migrations.AlterUniqueTogether(
            name='teamresults',
            unique_together={('teamid', 'year')},
        ),
    ]
