# Generated by Django 4.2 on 2023-04-19 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=32)),
                ('lastname', models.CharField(max_length=32)),
                ('displayname', models.CharField(max_length=32)),
                ('startyear', models.IntegerField()),
                ('endyear', models.IntegerField()),
                ('bbreflink', models.CharField(max_length=128)),
                ('rotowireid', models.CharField(blank=True, max_length=16, null=True)),
                ('position', models.CharField(max_length=8)),
                ('bats', models.CharField(blank=True, max_length=8, null=True)),
                ('throwhand', models.CharField(blank=True, max_length=8, null=True)),
                ('birthdate', models.CharField(blank=True, max_length=24, null=True)),
            ],
            options={
                'verbose_name': 'Player',
                'verbose_name_plural': 'Players',
                'db_table': 'players',
                'ordering': ['lastname', 'firstname'],
            },
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.IntegerField()),
                ('transdate', models.DateTimeField()),
                ('team1', models.IntegerField()),
                ('team2', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'db_table': 'transactions',
            },
        ),
        migrations.CreateModel(
            name='Rosterslot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playerid', models.ForeignKey(db_column='playerid', on_delete=django.db.models.deletion.CASCADE, to='player.players')),
                ('rosterid', models.ForeignKey(db_column='rosterid', on_delete=django.db.models.deletion.CASCADE, to='league.teams')),
            ],
            options={
                'db_table': 'rosterslot',
            },
        ),
        migrations.CreateModel(
            name='Rosters',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('season', models.IntegerField()),
                ('teamid', models.ForeignKey(db_column='teamid', on_delete=django.db.models.deletion.CASCADE, to='league.teams')),
            ],
            options={
                'db_table': 'rosters',
            },
        ),
        migrations.CreateModel(
            name='Rostermove',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.IntegerField()),
                ('resourcetype', models.IntegerField()),
                ('resourceid', models.IntegerField()),
                ('teamid', models.ForeignKey(db_column='teamid', on_delete=django.db.models.deletion.CASCADE, to='league.teams')),
                ('transactionid', models.ForeignKey(db_column='transactionid', on_delete=django.db.models.deletion.CASCADE, to='player.transactions')),
            ],
            options={
                'verbose_name': 'Transaction Item',
                'verbose_name_plural': 'Transaction Items',
                'db_table': 'rostermove',
            },
        ),
        migrations.CreateModel(
            name='Rosterassign',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('playerid', models.ForeignKey(db_column='playerid', on_delete=django.db.models.deletion.CASCADE, to='player.players')),
                ('teamid', models.ForeignKey(db_column='teamid', on_delete=django.db.models.deletion.CASCADE, to='league.teams')),
            ],
            options={
                'verbose_name': 'Roster Assignment',
                'verbose_name_plural': 'Roster Assignments',
                'db_table': 'rosterassign',
                'unique_together': {('playerid', 'teamid', 'year')},
            },
        ),
        migrations.CreateModel(
            name='Playercuts',
            fields=[
                ('playerid', models.OneToOneField(db_column='playerid', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='player.players')),
                ('season', models.IntegerField()),
                ('teamid', models.ForeignKey(db_column='teamid', on_delete=django.db.models.deletion.CASCADE, to='league.teams')),
            ],
            options={
                'db_table': 'playercuts',
            },
        ),
        migrations.CreateModel(
            name='CardedPlayers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('playername', models.CharField(max_length=64)),
                ('season', models.IntegerField()),
                ('mlbteam', models.CharField(blank=True, max_length=64, null=True)),
                ('playerid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='player.players')),
            ],
            options={
                'verbose_name': 'Carded Player',
                'verbose_name_plural': 'Carded Players',
                'db_table': 'cardedplayers',
                'unique_together': {('playerid', 'season')},
            },
        ),
    ]
