# Generated by Django 4.2 on 2023-04-21 20:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("player", "0004_players_bbrefid"),
    ]

    operations = [
        migrations.AddField(
            model_name="players",
            name="fangraphsid",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
