# Generated by Django 4.2 on 2023-04-21 21:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("player", "0005_players_fangraphsid"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="players",
            constraint=models.UniqueConstraint(
                fields=("bbrefid",), name="unique_bbrefid"
            ),
        ),
    ]
