# Generated by Django 4.2 on 2023-04-27 02:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("player", "0006_players_unique_bbrefid"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="transactions",
            index=models.Index(fields=["id", "type"], name="transactions_id_type_idx"),
        ),
        migrations.AddIndex(
            model_name="transactions",
            index=models.Index(fields=["team1"], name="transactions_team1_idx"),
        ),
    ]
