# Generated by Django 4.2 on 2023-04-26 00:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("draft", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="draftorder",
            options={},
        ),
        migrations.AlterModelOptions(
            name="draftpicks",
            options={
                "verbose_name": "Draft Pick",
                "verbose_name_plural": "Draft Picks",
            },
        ),
    ]
