# Generated by Django 4.2 on 2023-04-28 02:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("draft", "0004_draftpicks_draftpicks_draftyear_teams_idx_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="draftpicks",
            index=models.Index(fields=["draftyear"], name="draftpicks_draftyear_idx"),
        ),
    ]
