# Generated by Django 4.2 on 2023-04-19 02:23

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Divisions",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Division",
                "verbose_name_plural": "Divisions",
                "db_table": "divisions",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Emailaddresses",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("address", models.CharField(max_length=64)),
                ("primaryaddress", models.CharField(max_length=2)),
            ],
            options={
                "verbose_name": "Email Address",
                "verbose_name_plural": "Email Addresses",
                "db_table": "emailaddresses",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Idgen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nextval", models.IntegerField()),
            ],
            options={
                "db_table": "idgen",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Leagues",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "League",
                "verbose_name_plural": "Leagues",
                "db_table": "leagues",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Members",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("firstname", models.CharField(max_length=255)),
                ("lastname", models.CharField(max_length=255)),
                ("streetaddress1", models.CharField(max_length=255)),
                (
                    "streetaddress2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("city", models.CharField(max_length=255)),
                ("state", models.CharField(max_length=255)),
                ("zipcode", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Member",
                "verbose_name_plural": "Members",
                "db_table": "members",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Phonenumbers",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("phonenumber", models.CharField(max_length=25)),
                ("workorhome", models.CharField(max_length=2)),
            ],
            options={
                "verbose_name": "Phone Number",
                "verbose_name_plural": "Phone Numbers",
                "db_table": "phonenumbers",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Schedules",
            fields=[
                ("year", models.IntegerField()),
                ("seriesid", models.AutoField(primary_key=True, serialize=False)),
                ("homewins", models.IntegerField(default="0")),
                ("visitwins", models.IntegerField(default="0")),
                ("numgames", models.IntegerField(default="3")),
                ("dateplayed", models.DateTimeField(blank=True, null=True)),
                (
                    "playmonth",
                    models.IntegerField(
                        choices=[
                            (5, "May"),
                            (6, "Jun"),
                            (7, "Jul"),
                            (8, "Aug"),
                            (9, "Sept"),
                            (10, "Oct"),
                            (11, "Nov"),
                            (12, "Dec"),
                            (13, "Jan"),
                        ]
                    ),
                ),
                ("monthidx", models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)])),
            ],
            options={
                "verbose_name": "Schedule",
                "verbose_name_plural": "Schedules",
                "db_table": "schedules",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Teams",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("city", models.CharField(max_length=255)),
                ("nickname", models.CharField(max_length=255)),
                ("predecessor", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Team",
                "verbose_name_plural": "Teams",
                "db_table": "teams",
                "ordering": ["city", "nickname"],
                "managed": False,
            },
        ),
    ]
