# Generated by Django 4.2 on 2023-04-26 00:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("league", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="divisions",
            options={"verbose_name": "Division", "verbose_name_plural": "Divisions"},
        ),
        migrations.AlterModelOptions(
            name="emailaddresses",
            options={
                "verbose_name": "Email Address",
                "verbose_name_plural": "Email Addresses",
            },
        ),
        migrations.AlterModelOptions(
            name="idgen",
            options={},
        ),
        migrations.AlterModelOptions(
            name="leagues",
            options={"verbose_name": "League", "verbose_name_plural": "Leagues"},
        ),
        migrations.AlterModelOptions(
            name="members",
            options={"verbose_name": "Member", "verbose_name_plural": "Members"},
        ),
        migrations.AlterModelOptions(
            name="phonenumbers",
            options={
                "verbose_name": "Phone Number",
                "verbose_name_plural": "Phone Numbers",
            },
        ),
        migrations.AlterModelOptions(
            name="schedules",
            options={"verbose_name": "Schedule", "verbose_name_plural": "Schedules"},
        ),
        migrations.AlterModelOptions(
            name="teams",
            options={
                "ordering": ["city", "nickname"],
                "verbose_name": "Team",
                "verbose_name_plural": "Teams",
            },
        ),
    ]
